### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by rohit-gohri** [rohit-smpx/hello-ci-frontend#1]
- [x] Init repo with CRA (create basic landing page)
- [x] Add basic Drone.io pipeline:
  - [ ] Lint
  - [x] Test
  - [x] Build
  - [x] Deploy with Now
